# packages in environment at /home/ec2-user/anaconda3/envs/atac:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
_r-mutex                  1.0.0               anacondar_1  
argon2-cffi               20.1.0           py36h27cfd23_1  
asn1crypto                1.4.0                      py_0  
async_generator           1.10             py36h28b3542_0  
atropos                   1.1.25           py36h516909a_0    bioconda
attrs                     21.4.0             pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
bcrypt                    3.2.0            py36h7b6447c_0  
bedtools                  2.30.0               h7d7f7ad_1    bioconda
blas                      1.0                         mkl  
bleach                    1.4.2                    py36_0    bioconda
bowtie                    1.2.0                    py36_0    bioconda
bowtie2                   2.3.5.1          py36he513fc3_0    bioconda
brotlipy                  0.7.0           py36h27cfd23_1003  
bz2file                   0.98             py36h06a4308_1  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2022.10.11           h06a4308_0  
cairo                     1.14.12              h8948797_3  
certifi                   2021.5.30        py36h06a4308_0  
cffi                      1.14.0           py36h2e261b9_0  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
cryptography              2.3.1            py36hc365091_0  
curl                      7.55.1               h78862de_4  
cutadapt                  1.18             py36h14c3975_1    bioconda
cycler                    0.11.0             pyhd3eb1b0_0  
dbus                      1.13.18              hb2f20db_0  
decorator                 5.1.1              pyhd3eb1b0_0  
deeptools                 3.5.1                      py_0    bioconda
deeptoolsintervals        0.1.9            py36h516909a_0    bioconda
defusedxml                0.7.1              pyhd3eb1b0_0  
docutils                  0.17.1           py36h06a4308_1  
dropbox                   5.2.1                    py36_0    bioconda
entrypoints               0.3                      py36_0  
et-xmlfile                1.1.0                    pypi_0    pypi
expat                     2.4.4                h295c915_0  
fastqc                    0.11.9               hdfd78af_1    bioconda
fhtbioinfpy               0.0.1                     dev_0    <develop>
filechunkio               1.6                      py36_0    bioconda
font-ttf-dejavu-sans-mono 2.37                 hd3eb1b0_0  
fontconfig                2.13.1               h6c09931_0  
freetype                  2.11.0               h70c0345_0  
fribidi                   1.0.10               h7b6447c_0  
ftputil                   3.2                      py36_0    bioconda
glib                      2.63.1               h5a9c865_0  
graphite2                 1.3.14               h23475e2_0  
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
harfbuzz                  1.8.8                hffaf4a1_0  
html5lib                  1.1                pyhd3eb1b0_0  
icu                       58.2                 he6710b0_3  
idna                      3.3                pyhd3eb1b0_0  
idr                       2.0.4.2          py36hc1659b7_2    bioconda
importlib-metadata        3.10.0           py36h06a4308_0  
importlib_metadata        3.10.0               hd3eb1b0_0  
intel-openmp              2022.0.1          h06a4308_3633  
ipykernel                 5.3.4            py36h5ca1d4c_0  
ipython                   7.16.1           py36h5ca1d4c_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                7.6.5              pyhd3eb1b0_1  
jedi                      0.17.0                   py36_0  
jinja2                    3.0.2              pyhd3eb1b0_0  
jpeg                      9d                   h7f8727e_0  
jsonschema                3.2.0              pyhd3eb1b0_2  
jupyter                   1.0.0                    py36_7  
jupyter_client            7.1.2              pyhd3eb1b0_0  
jupyter_console           6.4.3              pyhd3eb1b0_0  
jupyter_core              4.8.1            py36h06a4308_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1  
kiwisolver                1.3.1            py36h2531618_0  
lcms2                     2.12                 h3be6417_0  
libcurl                   7.61.1               heec0ca6_0  
libdeflate                1.0                  h14c3975_1    bioconda
libedit                   3.1.20210910         h7f8727e_0  
libffi                    3.2.1             hf484d3e_1007  
libgcc                    7.2.0                h69d50b8_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgfortran-ng            7.5.0               ha8ba4b0_17  
libgfortran4              7.5.0               ha8ba4b0_17  
libgomp                   9.3.0               h5101ec6_17  
libpng                    1.6.37               hbc83047_0  
libsodium                 1.0.18               h7b6447c_0  
libssh2                   1.8.0                h9cfc8f7_4  
libstdcxx-ng              9.3.0               hd4cf53a_17  
libtiff                   4.2.0                h85742a9_0  
libuuid                   1.0.3                h7f8727e_2  
libwebp-base              1.2.2                h7f8727e_0  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.12               h03d6c58_0  
lz4-c                     1.9.3                h295c915_1  
macs2                     2.2.6            py36h516909a_0    bioconda
markupsafe                2.0.1            py36h27cfd23_0  
matplotlib                3.3.4            py36h06a4308_0  
matplotlib-base           3.3.4            py36h62a2d02_0  
mistune                   0.8.4            py36h7b6447c_0  
mkl                       2020.2                      256  
mkl-service               2.3.0            py36he8ac12f_0  
mkl_fft                   1.3.0            py36h54f3939_0  
mkl_random                1.1.1            py36h0573a6f_0  
mysql                     5.7.20               h55eaa98_0  
mysql-connector-c         6.1.6                         2    bioconda
nbclient                  0.5.3              pyhd3eb1b0_0  
nbconvert                 6.0.7                    py36_0  
nbformat                  5.1.3              pyhd3eb1b0_0  
ncurses                   6.3                  h7f8727e_2  
nest-asyncio              1.5.1              pyhd3eb1b0_0  
ninja                     1.10.2               h5e70eb0_2  
notebook                  6.4.0            py36h06a4308_0  
numpy                     1.17.0                   pypi_0    pypi
numpy-base                1.19.2           py36hfa32c7d_0  
olefile                   0.46                     py36_0  
openjdk                   8.0.152              h7b6447c_3  
openpyxl                  3.2.0b1                  pypi_0    pypi
openssl                   1.0.2u               h7b6447c_0  
pandas                    1.1.3            py36he6710b0_0  
pandoc                    2.12                 h06a4308_0  
pandocfilters             1.5.0              pyhd3eb1b0_0  
pango                     1.42.4               h049681c_0  
paramiko                  2.4.2                    py36_0  
parso                     0.8.3              pyhd3eb1b0_0  
pcre                      8.45                 h295c915_0  
perl                      5.26.2               h14c3975_0  
perl-threaded             5.32.1               hdfd78af_1    bioconda
pexpect                   4.8.0              pyhd3eb1b0_3  
picard                    2.26.11              hdfd78af_0    bioconda
pickleshare               0.7.5           pyhd3eb1b0_1003  
pigz                      2.6                  h27cfd23_0  
pillow                    8.2.0            py36he98fc37_0  
pip                       21.2.2           py36h06a4308_0  
pixman                    0.40.0               h7f8727e_1  
plotly                    5.6.0              pyhd3eb1b0_0  
prometheus_client         0.13.1             pyhd3eb1b0_0  
prompt-toolkit            3.0.20             pyhd3eb1b0_0  
prompt_toolkit            3.0.20               hd3eb1b0_0  
psutil                    5.8.0            py36h27cfd23_1  
ptyprocess                0.7.0              pyhd3eb1b0_2  
py2bit                    0.3.0            py36h14c3975_2    bioconda
pyasn1                    0.4.8              pyhd3eb1b0_0  
pybigwig                  0.3.13           py36h92ddc84_1    bioconda
pycparser                 2.21               pyhd3eb1b0_0  
pygments                  2.11.2             pyhd3eb1b0_0  
pynacl                    1.4.0            py36h7b6447c_1  
pyopenssl                 19.0.0                   py36_0  
pyparsing                 3.0.4              pyhd3eb1b0_0  
pyqt                      5.9.2            py36h05f1152_2  
pyrsistent                0.17.3           py36h7b6447c_0  
pysam                     0.15.3           py36hda2845c_1    bioconda
pysftp                    0.2.9                    py36_0    bioconda
pysocks                   1.7.1            py36h06a4308_0  
python                    3.6.6                h6e4f718_2  
python-dateutil           2.8.2              pyhd3eb1b0_0  
pytorch-cpu               1.1.0               py3.6_cpu_0    pytorch
pytz                      2022.1                   pypi_0    pypi
pyyaml                    5.4.1            py36h27cfd23_1  
pyzmq                     22.2.1           py36h295c915_1  
qt                        5.9.6                h8703b6f_2  
qtconsole                 5.2.2              pyhd3eb1b0_0  
qtpy                      1.11.2             pyhd3eb1b0_0  
r-base                    3.2.2                         0  
readline                  7.0                  h7b6447c_5  
requests                  2.27.1             pyhd3eb1b0_0  
samtools                  1.7                           1    bioconda
scipy                     1.5.2            py36h0b6359f_0  
send2trash                1.8.0              pyhd3eb1b0_1  
setuptools                58.0.4           py36h06a4308_0  
sip                       4.19.8           py36hf484d3e_0  
six                       1.16.0             pyhd3eb1b0_1  
snakemake                 3.13.3                   py36_0    bioconda
sqlite                    3.33.0               h62c20be_0  
subread                   2.0.1                h5bf99c6_1    bioconda
tbb                       2020.2               hff7bd54_0  
tenacity                  8.0.1            py36h06a4308_0  
terminado                 0.9.4            py36h06a4308_0  
testpath                  0.5.0              pyhd3eb1b0_0  
tk                        8.6.11               h1ccaba5_0  
tornado                   6.1              py36h27cfd23_0  
tqdm                      4.7.2                    py36_0    bioconda
traitlets                 4.3.3            py36h06a4308_0  
typing_extensions         3.10.0.2           pyh06a4308_0  
ucsc-bedclip              332                           0    bioconda
ucsc-bedgraphtobigwig     357                           1    bioconda
urllib3                   1.26.8             pyhd3eb1b0_0  
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1                    py36_1  
wheel                     0.37.1             pyhd3eb1b0_0  
widgetsnbextension        3.5.1                    py36_0  
wrapt                     1.12.1           py36h7b6447c_1  
xopen                     0.7.3                      py_0    bioconda
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0  
zeromq                    4.3.4                h2531618_0  
zipp                      3.4.1              pyhd3eb1b0_0  
zlib                      1.2.11               h7f8727e_4  
zstd                      1.4.9                haebb681_0  
